spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training?training=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Japan
    username: training
    password: training